### ISSUE TITLE
Allow TYPO3 version 9

### ISSUE THREAD

**Issue by sbusemann** [in2code-de/t3am#4]
As a user, i want to be able, to login at TYPO3 version 9 installations

**AC**
- [x] authentication is possible, via TYPO3 version 9
- [x] resolve #81536 - MoveOfServicesListReportFromSvToReports  in Authenticator
- [x] resolve #80929 - TYPO3_DB moved to extension in UserRespository
- [x] resolve #82254 - Deprecate $GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf'] in extConf
- [x] resolve #82254 - Deprecate $GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf'] in classes/Config.php
